### PR TITLE
Cartpole hyperparams

### PR DESCRIPTION
**Pull request by Bam4d**
## What changes were proposed in this pull request?

Significantly better hyperparameter choices for cartpole. DQN trains significantly faster

## How was this patch tested?

Manual tests:
new hyperparameters reach optimal in about 50 epochs.
Previous hyperparameters don't appear to reach optimal score.

### CODE REVIEW

**Comment by saudet** [comment]
@RobAltena and @treo are working on these examples these days

**Review by saudet — CHANGES_REQUESTED** [review]
Please don't undo updates made by others.

**Comment by treo** [comment]
@Bam4d can you please rebase this branch on master, so it's easier to see your actual changes?

**Comment by Bam4d** [comment]
Closing in favour of https://github.com/KonduitAI/deeplearning4j-examples/pull/5 as rebase was not working due to eclipse/konduit conflicts

**Pull request closed without merging**
